# Generated by Django 5.0.1 on 2024-05-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_noterestaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='noteRestaurant',
            field=models.FloatField(default=0, null=True),
        ),
    ]
