# Generated by Django 5.0.1 on 2024-05-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_noterestaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='noteRestaurant',
        ),
    ]
