# Generated by Django 5.0.1 on 2024-05-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_remove_restaurant_noterestaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='noteRestaurant',
            field=models.FloatField(null=True),
        ),
    ]
