# Generated by Django 5.0.1 on 2024-05-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_noterestaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='imageRestaurant',
            field=models.URLField(default='https://example.com/default_image.jpg'),
        ),
    ]
