# Generated by Django 5.0.1 on 2025-04-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='adresseRestaurant',
            field=models.CharField(default='Adresse inconnue', max_length=100),
        ),
    ]
