# Generated by Django 5.0.1 on 2025-04-18 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_restaurant_adresserestaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='noRestaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='adresseRestaurant',
            field=models.CharField(default='Inconnue', max_length=100),
        ),
    ]
