# Generated by Django 5.0.1 on 2025-04-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_alter_commentaire_norestaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='old_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
