# Generated by Django 5.0.1 on 2025-04-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_log_old_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='new_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
