# Generated by Django 5.0.1 on 2025-04-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_log_new_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='old_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
