# Generated by Django 5.0.1 on 2025-04-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_commentaire_old_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='nomRestaurant',
            field=models.CharField(max_length=255),
        ),
    ]
